### ISSUE TITLE
Integrate Search API /search/{fragment}

### ISSUE THREAD

**Issue by persia92** [vslee/IEXSharp#1]
Hi,
I couldn't find this api in here under Reference Data section.
GET /search/{fragment}
https://iexcloud.io/docs/api/#search

**Comment by vslee** [comment]
This library is currently undergoing an overhaul. It will probably stabilize in a couple of weeks.

**Comment by Matthiee** [comment]
Hi @vslee 

I also would like to have this feature. 

> This library is currently undergoing an overhaul. It will probably stabilize in a couple of weeks.

If it is stable enough, I can work on it and submit a PR. 

Let me know.
