### ISSUE TITLE
Missing endpoints

### ISSUE THREAD

**Issue by dominiclapointe** [vslee/IEXSharp#100]
Hi,

I am getting started with IEXSharp and IEXCloud. At the moment, im mostly testing the functionalities of your client, which seem to be quite nice!

There is 3 endpoints that doesn't seem to be existing in your current client
1.  GET /stock/{symbol}/recommendation-trends
2. GET /stock/{symbol}/estimates
3. GET /stock/{symbol}/price-target

Is there any plan to integrate these endpoints (and maybe also GET /stock/{symbol}/earnings/{last}/{field}) ? 

Thank you

ps: good job for your client, pretty amazing and well done!

**Comment by vslee** [comment]
The endpoints you mentioned already exist in `StockResearchService` and `StockFundamentalsService`. FYI, the library is organized exactly the same way as in the documentation here [https://iexcloud.io/docs/api](https://iexcloud.io/docs/api). Please review that document carefully.

**Comment by JamiePrentice** [comment]
I'm wondering if IEXCloud have shuffled these around @vslee 

It looks like they're under premium data - https://iexcloud.io/docs/api/#estimates-data - I don't remember them being there before. Will have a look into it
