### ISSUE TITLE
Examples for using QueryStringBuilder

### ISSUE THREAD

**Issue by ManfredLange** [vslee/IEXSharp#102]
While generally it shouldn't be too hard to use the QueryStringBuilder, it'd be great if either in the tests or in the wiki (or both?) there would be some examples for how to use the QueryStringBuilder, e.g. for the `qsb` parameter in `IStockPricesService.HistoricalPriceAsync()`.

Perhaps such examples already exist. Then perhaps adding a link in the README.md or in the wiki (or both?) would be helpful.

Thank you and keep up the good work!

**Comment by Matthiee** [comment]
If you check the implementation of `IStockPricesService` you can see some usages of it. 
https://github.com/vslee/IEXSharp/blob/c867f1025b2125b03e5d9ca3f30626c158991958/IEXSharp/Service/Cloud/CoreData/StockPrices/StockPricesService.cs#L55-L57

**Comment by ManfredLange** [comment]
That provides a starting point. Thank you!
