### ISSUE TITLE
JSON Parsing error HistoricalPriceAsync

### ISSUE THREAD

**Issue by drewsmi2001** [vslee/IEXSharp#110]
Hello:

This might be similar to the other 'open' issue.  When executing the following query, receive error message:

var response = await iexCloudClient.StockPrices.HistoricalPriceAsync("WWR", ChartRange.TwoYears);

Error:
Inner Exception: {"The JSON value could not be converted to System.Nullable`1[System.Int64]. Path: $[0].volume | LineNumber: 0 | BytePositionInLine: 88."}

Message: Either the JSON value is not in a supported format, or is out of bounds for an Int64.
Message: [{"close":9.5,"high":9.5,"low":7.575,"open":9,"symbol":"WWR","volume":30076.100000000006,"id":"HISTORICAL_PRICES","key":"WWR","subkey":"","date":"2019-04-22","updated":1606830572000,"changeOverTime":0,"marketChangeOverTime":0,"uOpen":0.18,"uClose":0.19,"uHigh":0.19,"uLow":0.1515,"uVolume":1503805,"fOpen":9,"fClose":9.5,"fHigh":9.5,"fLow":7.575,"fVolume":30076.100000000006,"label":"Apr 22, 19","change":0,"changePercent":0}, ........

Thanks.

**Comment by vslee** [comment]
Looks like you're using an old version. Try updating.

**Comment by drewsmi2001** [comment]
Yes, that was it.  Thank you.
