### ISSUE TITLE
PFF(ETF) parsing error with DividendsAdvancedAsync function 

### ISSUE THREAD

**Issue by libu1129** [vslee/IEXSharp#111]
When importing PFF data with the DividendsAdvancedAsync function, an error occurs saying that NULL cannot be parsed as INT.

**Comment by libu1129** [comment]
The JSON value could not be converted to System.Nullable`1[System.Int32]. Path: $[13].isNetInvestmentIncome | LineNumber: 0 | BytePositionInLine: 15312.

**Comment by libu1129** [comment]
public int? isNetInvestmentIncome { get; set; }
to
public bool? isNetInvestmentIncome { get; set; }
solved

**Comment by vslee** [comment]
Thanks for your figuring this out! The fix is now incorporated into the [latest pre-release](https://github.com/vslee/IEXSharp/wiki/Use-GitHub-Packages-with-Visual-Studio).
