### ISSUE TITLE
JSON Value Cannot be Converted to System.Nullable

### ISSUE THREAD

**Issue by drewsmi2001** [vslee/IEXSharp#116]
System has been running fine without issue for over a year.  Running under version 2.8.0.
Attempting to retrieve quote for AMD via the following:

                var response = await iexCloudClient.StockPrices.HistoricalPriceAsync(symbol, ChartRange.ThreeMonths);

Results in:
{"The JSON value could not be converted to System.Nullable`1[System.Int64]. Path: $[0].updated | LineNumber: 0 | BytePositionInLine: 184."}

Inner Exception:
Either the JSON value is not in a supported format, or is out of bounds for an Int64.

Data results have been attached.  What am I missing?  Seems any value expecting int64 could be set to 0 but not following how can't be set to System.Nullable.  Any pointers appreciated.
[IEXDataError.txt](https://github.com/vslee/IEXSharp/files/8262846/IEXDataError.txt)

**Comment by vslee** [comment]
Should be fixed now. Can you try the [latest pre-release](https://github.com/vslee/IEXSharp/wiki/Use-GitHub-Packages-with-Visual-Studio)?

**Comment by drewsmi2001** [comment]
Have tried latest pre-release and my issue has been resolved.  Much appreciated.
