### ISSUE TITLE
Error When Pulling Dividend Informaiton

### ISSUE THREAD

**Issue by Calm8809** [vslee/IEXSharp#117]
Hello all. When pulling dividend information I get the following error:
`The JSON value could not be converted to System.Int64`
Here's the data I receive:
`[{"amount":1.9,"currency":"USD","declaredDate":"2022-02-22","description":"Ordinary Shares","exDate":"2022-03-09","flag":"Cash","frequency":"quarterly","paymentDate":"2022-03-24","recordDate":"2022-03-10","refid":2452707,"symbol":"HD","id":"DIVIDENDS","key":"HD","subkey":"2452707","date":1646784000000,"updated":1647302657303.492}]`

**Comment by vslee** [comment]
Should be fixed now. Can you try the [latest pre-release](https://github.com/vslee/IEXSharp/wiki/Use-GitHub-Packages-with-Visual-Studio)?

**Comment by Calm8809** [comment]
Looks great to me. Thank you!
