### ISSUE TITLE
Support for technical indicators

### ISSUE THREAD

**Issue by johannord** [vslee/IEXSharp#3]
Hi,

Do you have any immediate plans to add support for technical indicators (https://iexcloud.io/docs/api/#technical-indicators)? 

Cheers!

**Comment by vslee** [comment]
I probably won't get around to adding new endpoints for a while. If you'd like to send a pull request with the new code, I'd be happy to merge it. If you don't know how, you can also post the code as a comment here.

**Comment by johannord** [comment]
As soon as I'll find the time, I'll make an effort :) 

IEX APIs scale quite well right (100 requests / second)? Otherwise just noticed from code inspection that backoff / retry policies and such could've been a nice add for theAPI  client.

**Comment by vslee** [comment]
I have not tried sending requests that quickly. 
Incorporating rate limiting would be a good feature though.
