### ISSUE TITLE
BatchType needs peers

### ISSUE THREAD

**Issue by szadrutsky** [vslee/IEXSharp#4]
Would be great to add peers to the batch type.
Its a separate call in the lib now however API supports peers in a batch call.

https://cloud.iexapis.com/stable/stock/msft/batch?types=quote,news,peers,chart&range=1d&last=5&token={token}

**Comment by vslee** [comment]
I probably won't get around to adding new endpoints for a while. If you'd like to send a pull request with the new code, I'd be happy to merge it. If you don't know how, you can also post the code as a comment here.
