### ISSUE TITLE
Add DEEP book streaming for US Stocks and Crypto

### ISSUE THREAD

**Issue by antonma** [vslee/IEXSharp#58]
Hey All,

love this package! Please could you add DEER Book calls for US Stocks and Crypto which is mentioned here in the API description:

https://iexcloud.io/docs/api/

curl --header 'Accept: text/event-stream' https://cloud-sse.iexapis.com/stable/deep?token=YOUR_TOKEN&symbols=twtr&channels=book

curl --header 'Accept: text/event-stream' https://cloud-sse.iexapis.com/stable/cryptoBook\?symbols\=btcusd\&token\=YOUR_TOKEN

This would be awesome!
Thank you

**Comment by JamiePrentice** [comment]
I’ll look into picking this up. I think I either avoided it at the time or was under the impression it was complete.

API docs with anchor link: https://iexcloud.io/docs/api/#deep

**Comment by JamiePrentice** [comment]
Ah! I knew I'd seen this before.

We do already have an implementation of the calls to the deep book, see a usage here:

https://github.com/vslee/IEXSharp/blob/master/IEXSharpTest/Cloud/CoreData/InvestorsExchangeDataTest.cs#L46

However we're missing the streaming side of things.

@vslee I scanned through the documents and the code previously to verify completeness, but I didn't check on streaming, only http requests. I'll start and work my way through what's missing when I get some time.
