### ISSUE TITLE
Support advanced dividends

### ISSUE THREAD

**Issue by Matthiee** [vslee/IEXSharp#6]
Hi

Are there any plans to support the advanced dividends endpoint?

Docs: https://iexcloud.io/docs/api/#dividends

**Comment by vslee** [comment]
I probably won't get around to adding new endpoints for a while. If you'd like to send a pull request with the new code, I'd be happy to merge it. If you don't know how, you can also post the code as a comment here.

**Comment by Matthiee** [comment]
I'll try to submit a PR somewhere this week!
