### ISSUE TITLE
BatchResponse properties don't get populated

### ISSUE THREAD

**Issue by abrull** [vslee/IEXSharp#64]
Hi, I'm trying to create a batch request and in fiddler I see that the values come in via the API, but when trying to get the values through response.Data (BatchResponse) all of the properties are null

**Comment by vslee** [comment]
What parameters are you using?

**Comment by abrull** [comment]
this is my code
`var client = new IEXCloudClient("pk_*****************************", "sk_***********************************", signRequest: true, useSandBox: false);

var response = await client.Batch.BatchBySymbolAsync("AAPL", new[] { BatchType.News, BatchType.Quote, BatchType.Chart, BatchType.Price }, last: 5);`
Note I have the Launch plan (individual) on IEX

**Comment by abrull** [comment]
Thanks for the quick response
