### ISSUE TITLE
KeyStatsStatAsync throws error

### ISSUE THREAD

**Issue by MikeCoderr** [vslee/IEXSharp#8]
Hi,

When I execute below code, I get an error like this (sure enough my Tokens are in there):
**Child “token” fails beause [“token” must be a string**

```
using (var iexCloudClient = new IEXCloudClient("pk_", "sk_", signRequest: true, useSandBox: false))
            {
                var response = await iexCloudClient.Stock.KeyStatsStatAsync("AAPL", "marketCap");
                if (response.ErrorMessage != null)
                {
                    Console.WriteLine(response.ErrorMessage);
                }
                else
                {
                    Console.WriteLine(response.Data.marketcap);
                }
            }
```
Any ideas what could be the issue?

**Comment by vslee** [comment]
Okay, should be fixed now. FYI, the stat is `marketcap` all lowercase. If you want to try out the update, you'll have to get the latest prerelease from [GH Packages](https://github.com/vslee/IEXSharp/packages)

**Comment by MikeCoderr** [comment]
Thanks. 

Same issue as above happens here:
`var response = await iexCloudClient.Stock.QuoteFieldAsync("AAPL", "marketcap");`

maybe you can fix that as well

**Comment by vslee** [comment]
Fixed. Note that for `QuoteFieldAsync()`, `marketCap` has a capital C
