### ISSUE TITLE
HistoricalPrices (Stocks) using the ChartRange.DateType

### ISSUE THREAD

**Issue by Shackman287** [vslee/IEXSharp#81]
I can use the ChartRange.DateType (as below), but I can't figure out how to input the desired date that I want to extract the minute-price history with. I know there is HistoricalPricesByDate, but this only provides the daily open/close, etc.. Do you know how I can specify the date, or a better way to extract minute based historical data. IEXcloud states on their page they make the previous 30 days minute-level data available for access.

-Great API! Love it's features and ease of use!
-Thank you

**Comment by vslee** [comment]
Did you try `HistoricalPriceByDateAsync()` and setting `chartByDay` to `false`?

**Comment by Shackman287** [comment]
LEE Thank you for the fast response.

I just learned after trying HistoricalPriceByDateAsync, that the day I was searching for was a WEEKEND! Ugh... Move to a weekday and it worked. Thank you for the response and appreciate your development work in this tool. Close the issue out :)
