### ISSUE TITLE
iexMarketPercent in QuoteSSE should be nullable

### ISSUE THREAD

**Issue by cduongt** [vslee/IEXSharp#83]
[{"symbol":"PALL","companyName":"Aberdeen Standard Physical Palladium Shares ETf","primaryExchange":"NYSE Arca","calculationPrice":"sip","open":219.74,"openTime":1606314600195,"openSource":"official","close":221.26,"closeTime":1606251600070,"closeSource":"official","high":220.5,"highTime":1606335998843,"highSource":"15 minute delayed price","low":219.2,"lowTime":1606316605077,"lowSource":"15 minute delayed price","latestPrice":220.1,"latestSource":"15 minute delayed price","latestTime":"3:23:24 PM","latestUpdate":1606335804130,"latestVolume":9632,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":220.1,"delayedPriceTime":1606335804130,"oddLotDelayedPrice":220.1,"oddLotDelayedPriceTime":1606335998843,"extendedPrice":219.5,"extendedChange":-0.6,"extendedChangePercent":-0.00273,"extendedPriceTime":1606314600806,"previousClose":221.26,"previousVolume":26308,"change":-1.16,"changePercent":-0.00524,"volume":9632,"iexMarketPercent":null,"iexVolume":0,"avgTotalVolume":27875,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":220.51,"iexAskSize":500,"iexOpen":null,"iexOpenTime":null,"iexClose":219.94,"iexCloseTime":1606236000040,"marketCap":374170000,"peRatio":null,"week52High":273.16,"week52Low":137.51,"ytdChange":0.194586,"lastTradeTime":1606335804130}] The JSON value could not be converted to System.Decimal. Path: $[0].iexMarketPercent | LineNumber: 0 | BytePositionInLine: 967.

**Comment by vslee** [comment]
Which endpoint is this?

**Comment by cduongt** [comment]
Should be the default non-sandbox SSE endpoint for QuoteStream, no UTP
