### ISSUE TITLE
Still {"The JSON value could not be converted to System.Decimal. Path: $[0].high | LineNumber: 0 | BytePositionInLine: 242."}

### ISSUE THREAD

**Issue by TobyBee** [vslee/IEXSharp#84]
Hey VsLee,

i am still getting the error with the system.decimal conversion :/.

i updated to 2.4.7 but the real time price still seems to be not nullable in the metadata for me.
i also reinstalled the package already. I love this library and i would like to keep using it :/.

Do you have an idea what could be the problem?

i attached two screenshot.

![Metadata](https://user-images.githubusercontent.com/38094015/101078010-e010b780-35a5-11eb-8aae-fe9ade3f0a72.JPG)
![Error](https://user-images.githubusercontent.com/38094015/101078014-e0a94e00-35a5-11eb-81c0-6c4366e4a3b9.JPG)

Thanks in advance & best regards 
Tobias

**Comment by vslee** [comment]
try 2.4.8
