### ISSUE TITLE
{"The JSON value could not be converted to System.Int64. Path: $.cashflow[0].dividendsPaid...!}

### ISSUE THREAD

**Issue by TobyBee** [vslee/IEXSharp#93]
HiLee,

i am getting the Json Error ("The JSON value could not be converted to System.Int64. Path: $.cashflow[0].dividendsPaid") again for the cashflow Statement. See Screenshot.

![image](https://user-images.githubusercontent.com/38094015/104135453-de9a9200-5390-11eb-9c1c-342edeea6ef7.png)

For the balanceSheet it works.

Best regards Tobias

**Comment by vslee** [comment]
This should be fixed by #90. Can you test the latest [prerelease](https://github.com/vslee/IEXSharp/packages/62376) to see if it is fixed there?

**Comment by vslee** [comment]
Closing as v2.6.0 is out now. Feel free to reopen if you're still having issues.
