### ISSUE TITLE
How can i get P/E ratio of a stock?

### ISSUE THREAD

**Issue by AlexRajvandary** [vslee/IEXSharp#96]
I tried this:
string ticker = "appl"// for example
IEXCloudClient client = new  new IEXCloudClient(.....);
 var stock = await client.StockFundamentals.AdvancedFundamentalsAsync(ticker);

why stock is null?

**Comment by vslee** [comment]
Try using AAPL instead of APPL

**Comment by AlexRajvandary** [comment]
Still null

**Comment by AlexRajvandary** [comment]
class Program
    {
        private static string public_token ="";
        private static string private_token = "";
        static async void GetStock(string ticker,IEXCloudClient client)
        {
            var stock = await client.StockFundamentals.AdvancedFundamentalsAsync(ticker);
            Console.WriteLine(stock.Data.symbol); 
  

        }
       
        static void Main(string[] args)
        {
            string ticker = "AAPL";
            public_token = File.ReadAllText("public_token.txt");
            private_token = File.ReadAllText("private_token.txt");

         

            IEXCloudClient client = new IEXCloudClient(public_token, private_token, false, false);
          
            GetStock(ticker, client);

            Console.ReadKey();

        }
    }
}



System.NullReferenceException

**Comment by JamiePrentice** [comment]
@AlexRajvandary, you appear to be trying to access https://iexcloud.io/docs/api/#advanced-fundamentals, and endpoint that is only available with paid IEX Cloud plans. I think this could be your problem. 

Failing that, you could log out error messages to help identify the issue by modifying your existing code like so:

``` c#
static async void GetStock(string ticker, IEXCloudClient client)
{
    IEXResponse<AdvancedFundamentalsResponse> iexResponse = 
                               await client.StockFundamentals.AdvancedFundamentalsAsync(ticker);
    if (iexResponse.ErrorMessage != null)
    {
        Console.WriteLine(iexResponse.ErrorMessage);
        return;
    }
    
    Console.WriteLine(iexResponse.Data.symbol);
}
```

**Comment by vslee** [comment]
Looks like there was a bug in our code, where AdvancedFundamentals returns an array and not a single value. 
But unrelated to that bug, it looks like IEX Cloud does not return anything for many companies when the period is set to `Quarter` instead of `Annual`.  So you can try it again, but modify your code to be:
```c#
            var stock = await client.StockFundamentals.AdvancedFundamentalsAsync(ticker, IEXSharp.Model.Shared.Request.Period.Annual);
```
Make sure you use the latest [prerelease](https://github.com/vslee/IEXSharp/wiki/Use-GitHub-Packages-with-Visual-Studio) or wait for the next official NuGet.

**Comment by JamiePrentice** [comment]
@vslee huh, not the angle I went for, but good catch on that, you're right.

**Comment by vslee** [comment]
@JamiePrentice I liked where you were going with teaching people how to help us w/ error messages though. 
And also that some data is not available to the lower plans.
