### ISSUE TITLE
IEXCloudClient.StockProfiles.CompanyAsync Bug decoding JSON

### ISSUE THREAD

**Issue by logikonline** [vslee/IEXSharp#99]
Retrieving the company info appears to have an invalid JSON object which you are trying to decode too.

Amazon being retrieved by this triggers the error.

{"symbol":"AMZN","companyName":"Amazon.com Inc.","exchange":"NASDAQ/NGS (GLOBAL SELECT MARKET)","industry":"Electronic Shopping and Mail-Order Houses ","website":"http://www.amazon.com/","description":"","CEO":"Jeffrey Bezos","securityName":"Amazon.com Inc.","issueType":"cs","sector":"Retail Trade","primarySicCode":5961,"employees":null,"tags":["Retail Trade","Internet Retail"],"address":"410 Terry Ave N","address2":null,"state":"Washington","city":"Seattle","zip":"98109-5210","country":"US","phone":"12062661000"}

The JSON value could not be converted to System.Int32. Path: $.employees | LineNumber: 0 | BytePositionInLine: 338.  THe employees needs to be an Integer? not integer

**Comment by logikonline** [comment]
Saw this changed in the model - nuget doesn't reflect yet.

**Comment by vslee** [comment]
In the meantime, you can try the [latest pre-release NuGet](https://github.com/vslee/IEXSharp/wiki/Use-GitHub-Packages-with-Visual-Studio).

**Comment by kewur** [comment]
Just curious, what is the frequency in which you publish releases?

**Comment by vslee** [comment]
About once a month, so the next one is very soon.
